import "../../../globals.css";


export const metadata = {
    title: "Sign In | page.js",
    description: "Generated by create next app",
};

import {getUser} from '../../../../lib/auth'
import {redirect} from "next/navigation";

export default async function RootLayout({ children }) {

    const {session, user} = await getUser()

    if(session &&  user.role === "superadmin"){
        return redirect("/dashboard")
    }
    return (
        <div>
        {children}
        </div>
    );
}
